# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
 branches:
   include:
     - '*'

variables:
- name: BuildPlatform
  value: 'any cpu'
- name: BuildConfiguration
  value: 'release'
stages:
- stage: provision_env
  displayName: 'provision resources to prod env'
  condition: and((always(), contains(variables['Build.SourceBranch'], 'refs/heads/feature'))
  jobs: 
  - job: infra_provisioning
    variables: 
     -group: development
- stage: provision_dev_env
  displayName: 'provision resources to dev env'
  condition: and((always(), contains(variables['Build.SourceBranch'], 'refs/heads/feature'))
  jobs: 
  - job: infra_provisioning
    variables: 
     -group: development 
   